name: DeVotion CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Docker Image Build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker-compose build
          docker-compose push

  docker-pull-image:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: SSH and Pull Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}

        script: |
          cd /home/dv23-1

          if [ -d "DeVotion" ]; then
            echo "Directory 'DeVotion' exists. Pulling latest changes."
            cd DeVotion
            git pull origin main  # Adjust the branch name if necessary
          else
            echo "Directory 'DeVotion' does not exist. Cloning repository."
            git clone https://github.com/dave-andrew/DeVotion.git
          fi

          cd DeVotion

          docker compose -f docker-compose.server.yaml pull
          docker compose -f docker-compose.server.yaml down
          docker compose -f docker-compose.server.yaml up -d
          docker exec devotion-app php artisan migrate --force

